server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 请确保你的数据库 ssgl_db 已经创建，端口号根据你的实际情况修改(默认3306)
    url: jdbc:mysql://localhost:3307/ssgl_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "123456" # 【重要】请修改为你本地 MySQL 的密码

  thymeleaf:
    cache: false
    mode: HTML

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl